// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjGA2zbO2Ss-CELI-LP7D6wLsGdexZwyk',
    appId: '1:835075868677:web:a0ba07c811f0de7efaf46c',
    messagingSenderId: '835075868677',
    projectId: 'quiz-app-6a919',
    authDomain: 'quiz-app-6a919.firebaseapp.com',
    storageBucket: 'quiz-app-6a919.appspot.com',
    measurementId: 'G-VZXKZF3883',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz8B_J4t9GUGdUjskZkGJpKmER692fGbM',
    appId: '1:835075868677:android:bed4b0043bd1bde3faf46c',
    messagingSenderId: '835075868677',
    projectId: 'quiz-app-6a919',
    storageBucket: 'quiz-app-6a919.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBVTmYbtG0GNqRFs3QU-BHrEWhBiUK6VE',
    appId: '1:835075868677:ios:b2e3ac2d895736d0faf46c',
    messagingSenderId: '835075868677',
    projectId: 'quiz-app-6a919',
    storageBucket: 'quiz-app-6a919.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBVTmYbtG0GNqRFs3QU-BHrEWhBiUK6VE',
    appId: '1:835075868677:ios:24e98fa1e6e880cbfaf46c',
    messagingSenderId: '835075868677',
    projectId: 'quiz-app-6a919',
    storageBucket: 'quiz-app-6a919.appspot.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
